Fix setattr issue in canonizers.MergeBatchNorm (#208)
chr5tphr/zennit pull request #209
Opened 2024-07-19 16:44 UTC by karray

Fixes #208

2024-08-01 16:16 UTC, chr5tphr requested changes
Thanks a lot for the PR.

There remains a potential issue: Since we use the `torch.nn.Module`'s setattr to register a Parameter if it did not exist before, the Parameter may still be registered after the Canonizer is removed, since we set the attribute back to `None` without using the `Module`'s setattr, which would detect this change. We need to explicitly unregister the Parameter, i.e., by using `register_parameter` or the `Module`'s setattr explicitly only if the original bias was `None` in the Canonizer's `remove()`.

2025-07-12 06:50 UTC, chr5tphr commented
I reviewed this once more, and it turns out setting the parameter back to `None` is enough to unregister it again, so the issue I raised earlier is invalid.

I rebased and made a small edit, where I also fixed the styling of the long line and used the normal way to assign attributes, since this is equivalent to `setattr`.

2025-07-12 06:51 UTC, chr5tphr commented on src/zennit/canonizers.py
> +                   module, 'bias', torch.nn.Parameter(torch.zeros(1, device=module.weight.device, dtype=module.weight.dtype))
Added this as an edit.

2025-07-12 06:51 UTC, chr5tphr approved these changes

2025-07-12 07:06 UTC, merged

2025-07-14 14:55 UTC, karray commented
@chr5tphr btw, another idea is to mark new parameters so that they can be deleted on `remove`

For example:

```py
#...
for module in modules:
    if module.bias is None:
        module.bias = torch.nn.Parameter(torch.zeros(1, device=module.weight.device, dtype=module.weight.dtype))
        module.bias.is_temporary = True
```

2025-07-15 01:15 UTC, chr5tphr commented
Thanks for the reply!
I verified that setting an attribute that is a parameter to None does unregister it, so we do not need to explicitly delete it, as we store the parameter regardless of whether it was a torch.nn.Parameter, or None.